"""Removed followed table, now follower table is used with two indexes

Revision ID: 267dc89405d0
Revises: 64c8e0323e1e
Create Date: 2024-09-27 20:54:03.450069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267dc89405d0'
down_revision: Union[str, None] = '64c8e0323e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followeds')
    op.create_index(op.f('ix_followers_followed_id'), 'followers', ['followed_id'], unique=False)
    op.create_index(op.f('ix_followers_follower_id'), 'followers', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followers_follower_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_followed_id'), table_name='followers')
    op.create_table('followeds',
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='followeds_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followeds_follower_id_fkey'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name='followeds_pkey')
    )
    # ### end Alembic commands ###
