"""add ondelete cascade

Revision ID: 3979264d1df3
Revises: 267dc89405d0
Create Date: 2024-10-03 18:50:38.050636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3979264d1df3'
down_revision: Union[str, None] = '267dc89405d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('followers_follower_id_fkey', 'followers', type_='foreignkey')
    op.drop_constraint('followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_followed_id_fkey', 'followers', 'users', ['followed_id'], ['id'])
    op.create_foreign_key('followers_follower_id_fkey', 'followers', 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###
