"""Create first tables

Revision ID: 55e6fe16b610
Revises: 
Create Date: 2024-09-15 21:46:51.573103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55e6fe16b610"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followed_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    op.create_table(
        "users_goals",
        sa.Column("id_user", sa.UUID(), nullable=False),
        sa.Column("goal", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id_user", "goal"),
    )
    op.create_table(
        "users_interests",
        sa.Column("id_user", sa.UUID(), nullable=False),
        sa.Column(
            "interest",
            sa.Enum(
                "sports",
                "games",
                "science",
                "politics",
                "engineering",
                name="interests",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id_user", "interest"),
    )
    op.create_table(
        "users_twitsnaps",
        sa.Column("id_user", sa.UUID(), nullable=False),
        sa.Column("id_twitsnap", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id_user", "id_twitsnap"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_twitsnaps")
    op.drop_table("users_interests")
    op.drop_table("users_goals")
    op.drop_table("followers")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
