services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      # - PORT: 
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - ENV=production
  test:
    build:
      context: .
      target: development
    volumes:
      - .:/code
    environment:
      - ENV=test
    command: python3 -m unittest && pytest -s 
    depends_on:
      - app
