services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/code
    ports:
      - "3000:${PORT}"
    environment:
      ENV: development
      PORT: ${PORT}
    # command: tail -f /dev/null  

  app-prod:
    build:
      context: .
      target: production
    
    # ports:
    #   - "80:80"
    environment:
      ENV: production
      PORT: ${PORT}
  test:
    build:
      context: .
      target: development
    volumes:
      - .:/code
    environment:
      TEST_POSTGRES_URL: ${TEST_POSTGRES_URL}
      PORT: ${PORT}
      ENV: test
    command: pytest -s 
