services:
  - type: web
    runtime: docker
    name: Users
    plan: free
    envVars:
      - key: POSTGRES_URL
        sync: false
      - key: ENV
        value: production
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: docker build -t users --target production . && docker run -d -e POSTGRES_URL=${POSTGRES_URL} -e ENV=production users
    autoDeploy: true # Automatically deploy new changes

