services:
  - type: web
    runtime: docker
    name: Users
    plan: free
    envVars:
      - key: POSTGRES_URL
        sync: false
      # - key: PORT
      #   sync: false
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: docker build -t users --target production . && docker run -d -e POSTGRES_URL=${POSTGRES_URL} users
    autoDeploy: true # Automatically deploy new changes

