name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:27.2.0
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests
        run: docker compose up test -d --build

      - name: Tear down
        if: always()
        run: docker compose -f "docker-compose.yaml" down

        # - name: Set up Python
        #   uses: actions/setup-python@v4
        #   with:
        #     python-version: '3.12'

        # - name: Install dependencies
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install -r requirements.txt

        # - name: Run tests
        #   env:
        #     ENV: testing
        #   run: |
        #     pytest ./app/tests

      # - name: Trigger deployment
      #         if: ${{ github.event_name == 'push' }}
      #         run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
